apiVersion: operators.coreos.com/v1
kind: OperatorCondition
metadata:
  name: sample-operator
  namespace: operator-ns
spec:
  overrides:
    - type: Upgradeable
      status: True
      reason: "OperatorIsStable"
      message: "Forcing an upgrade to bypass bug state"
status:
  conditions:
    - type: Upgradeable
      status: False
      reason: "OperatorBusy"
      message: "Operator is currently busy with a critical task"
      lastTransitionTime: "2022-01-19T12:00:00Z"