apiVersion: v1
kind: Namespace
metadata:
  name: nginx-operator-ns
---
apiVersion: operator.example.com/v1alpha1
kind: NginxOperator
metadata:
  name: test-nginx-operator-cr
  namespace: nginx-operator-ns
spec:
  port: 8080
  replicas: 1